# Generated by Django 5.1.6 on 2025-03-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Problems",
        ),
    ]
