# Generated by Django 5.1.6 on 2025-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problems",
            old_name="answer",
            new_name="solution",
        ),
        migrations.RemoveField(
            model_name="problems",
            name="name",
        ),
        migrations.AddField(
            model_name="problems",
            name="difficulty",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="problems",
            name="title",
            field=models.CharField(default="title", max_length=200),
            preserve_default=False,
        ),
    ]
