# Generated by Django 5.1.6 on 2025-03-21 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "problems",
            "0002_rename_answer_problems_solution_remove_problems_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problems",
            name="solution",
        ),
        migrations.AddField(
            model_name="problems",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
