# Generated by Django 5.1.6 on 2025-04-10 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_testcase"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesubmission",
            name="execution_time",
            field=models.FloatField(
                blank=True, help_text="Execution time in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="problem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.problems",
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Wrong Answer", "Wrong Answer"),
                    ("Runtime Error", "Runtime Error"),
                    ("Time Limit Exceeded", "Time Limit Exceeded"),
                    ("Compilation Error", "Compilation Error"),
                    ("Error", "Error"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="verdict_details",
            field=models.TextField(
                blank=True,
                help_text="Detailed verdict info like failed test case",
                null=True,
            ),
        ),
    ]
