# Generated by Django 5.1.6 on 2025-04-27 04:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_testcase"),
        ("submissions", "0005_usercode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercode",
            unique_together={("user", "problem", "language")},
        ),
    ]
